export const DONE_CLICKED = 'DONE_CLICKED';
export const CANCEL_CLICKED = "CANCEL_CLICKED";
export const EDIT_MENU_CLICKED = "EDIT_MENU_CLICKED";
export const SHORTCUT_TAIL_CLICKED = "SHORTCUT_TAIL_CLICKED";
export const ADD_SHORTCUT = "ADD_SHORTCUT";
export const REMOVE_SHORTCUT = "REMOVE_SHORTCUT";
export const UPDATE_SHORTCUT = "UPDATE_SHORTCUT";
export const CLEAR_MODAL_PROPS = "CLEAR_MODAL_PROPS";
export const REMOVE_TAG = "REMOVE_TAG";
export const ADD_TAG = "ADD_TAG";
export const CREATE_TAG = "CREATE_TAG";
export const FECTH_TAGS = "FECTH_TAGS";
export const SEARCH_CLICKED = "SEARCH_CLICKED";
export const FILTER_BY_TAG = "FILTER_BY_TAG";
export const HANDLE_DROP = "HANDLE_DROP";
export const SHORTCUTS_FETCHED = "SHORTCUTS_FETCHED";
export const TAGS_FETCHED = "TAGS_FETCHED";
export const SHORTCUT_SELECTED = "SHORTCUT_SELECTED";
export const DELETE_SHORTCUTS = "DELETE_SHORTCUTS";
export const FAVOURITE_SHORTCUT= "FAVOURITE_SHORTCUT";
export const FETCH_FAVOURITES= "FETCH_FAVOURITES";





